"""Schema / Pydantic validation tests."""

import pytest
from pydantic import ValidationError

from app.schemas.user import UserCreate
from app.schemas.tournament import TournamentCreate, TournamentUpdate, TournamentStatusUpdate
from app.schemas.team import TeamCreate, TeamUpdate
from app.schemas.match import MatchCreate, MatchScoreUpdate, MatchResultWithdraw, GoalEventCreate
from app.schemas.player import PlayerCreate


# =====================================================================
# User schemas
# =====================================================================

class TestUserSchemas:
    def test_valid_user_create(self):
        u = UserCreate(username="alice", email="alice@example.com", password="Secret123", account_type="manager")
        assert u.username == "alice"

    def test_username_too_short(self):
        with pytest.raises(ValidationError):
            UserCreate(username="ab", email="a@b.com", password="Secret123", account_type="manager")

    def test_username_invalid_chars(self):
        with pytest.raises(ValidationError):
            UserCreate(username="no spaces!", email="a@b.com", password="Secret123", account_type="manager")

    def test_password_too_short(self):
        with pytest.raises(ValidationError):
            UserCreate(username="user", email="a@b.com", password="short", account_type="manager")

    def test_extra_fields_rejected(self):
        with pytest.raises(ValidationError):
            UserCreate(username="user", email="a@b.com", password="Secret123", account_type="manager", is_admin=True)

    def test_invalid_account_type(self):
        with pytest.raises(ValidationError):
            UserCreate(username="user", email="a@b.com", password="Secret123", account_type="admin")


# =====================================================================
# Tournament schemas
# =====================================================================

class TestTournamentSchemas:
    def test_valid_tournament_create(self):
        t = TournamentCreate(name="Cup")
        assert t.name == "Cup"
        assert t.slug is None  # auto-generated by server

    def test_tournament_name_too_short(self):
        with pytest.raises(ValidationError):
            TournamentCreate(name="X")

    def test_tournament_invalid_dates(self):
        with pytest.raises(ValidationError):
            TournamentCreate(name="Cup", start_date="2026-12-01", end_date="2026-11-01")

    def test_tournament_update_rejects_null_name(self):
        with pytest.raises(ValidationError):
            TournamentUpdate(name=None)

    def test_valid_status_update(self):
        s = TournamentStatusUpdate(status="published")
        assert s.status == "published"

    def test_invalid_status(self):
        with pytest.raises(ValidationError):
            TournamentStatusUpdate(status="active")


# =====================================================================
# Team schemas
# =====================================================================

class TestTeamSchemas:
    def test_valid_team_create(self):
        t = TeamCreate(tournament_id=1, name="Eagles")
        assert t.name == "Eagles"

    def test_team_name_too_short(self):
        with pytest.raises(ValidationError):
            TeamCreate(tournament_id=1, name="X")

    def test_team_update_rejects_null_name(self):
        with pytest.raises(ValidationError):
            TeamUpdate(name=None)


# =====================================================================
# Match schemas
# =====================================================================

class TestMatchSchemas:
    def test_match_date_requires_timezone(self):
        with pytest.raises(ValidationError):
            MatchCreate(
                tournament_id=1, home_team_id=1, away_team_id=2,
                match_date="2026-10-01T10:00:00",  # no timezone
            )

    def test_valid_match_create(self):
        m = MatchCreate(
            tournament_id=1, home_team_id=1, away_team_id=2,
            match_date="2026-10-01T10:00:00+05:00",
        )
        assert m.venue is None

    def test_score_update_negative_score_rejected(self):
        with pytest.raises(ValidationError):
            MatchScoreUpdate(home_score=-1, away_score=0, expected_version=1)

    def test_withdraw_requires_reason(self):
        with pytest.raises(ValidationError):
            MatchResultWithdraw(expected_version=1, reason="ab")  # too short

    def test_goal_event_minute_range(self):
        with pytest.raises(ValidationError):
            GoalEventCreate(scorer_id=1, minute=0)  # min is 1
        with pytest.raises(ValidationError):
            GoalEventCreate(scorer_id=1, minute=121)  # max is 120
        event = GoalEventCreate(scorer_id=1, minute=90)
        assert event.minute == 90


# =====================================================================
# Player schemas
# =====================================================================

class TestPlayerSchemas:
    def test_valid_player_create(self):
        p = PlayerCreate(team_id=1, name="Player")
        assert p.name == "Player"
